[package]
name = "kampfkarren/roblox"
license = "https://raw.githubusercontent.com/Kampfkarren/Roblox/master/LICENSE"
version = "1.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependecies]
